(cl:defpackage gazebo_video_monitor_msgs-srv
  (:use )
  (:export
   "SETCAMERA"
   "<SETCAMERA-REQUEST>"
   "SETCAMERA-REQUEST"
   "<SETCAMERA-RESPONSE>"
   "SETCAMERA-RESPONSE"
   "STARTGMCMRECORDING"
   "<STARTGMCMRECORDING-REQUEST>"
   "STARTGMCMRECORDING-REQUEST"
   "<STARTGMCMRECORDING-RESPONSE>"
   "STARTGMCMRECORDING-RESPONSE"
   "STARTGVMRECORDING"
   "<STARTGVMRECORDING-REQUEST>"
   "STARTGVMRECORDING-REQUEST"
   "<STARTGVMRECORDING-RESPONSE>"
   "STARTGVMRECORDING-RESPONSE"
   "STOPRECORDING"
   "<STOPRECORDING-REQUEST>"
   "STOPRECORDING-REQUEST"
   "<STOPRECORDING-RESPONSE>"
   "STOPRECORDING-RESPONSE"
  ))

